### ISSUE TITLE
使用SSH连接失败

### ISSUE THREAD

**Issue by LEUNGHOTIN** [goodspb/reedis#1]
首先，很感谢作者实现出了这么简洁的一个应用，很符合我的需求，但在最近的使用过程中发现了一个小问题

**场景：**
在使用个人私钥，通过SSH方式22022端口无密码的情况下，无法连接到远程机器内的Redis

**表现：**
点击connect按钮没有任何反应

**建议：**
希望能有个test connect以及连接别名的功能吧，不然是否连接得上，也没有太多的感知

再一次感谢作者的付出及贡献

**Comment by goodspb** [comment]
十分感谢关注&使用耶，我看看你说的问题，SSH 这块我没有很认真的测试过，主要是没有环境。我搭建个环境玩玩，感谢提出 issue

**Comment by goodspb** [comment]
发布了修复版本：https://github.com/goodspb/reedis/releases/tag/v0.1.0
